Repository manjunani/HacktoberFest_2021, pull requests merged in 2021-10, with the labels that each got.

#6 Binary Search
  DSA/C/BinarySearch.c
  DSA/C/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted

#7 added Iris Machine Learning file
  .DS_Store
  MLProjects/.DS_Store
  MLProjects/iris-machine-learning-master/IRIS.csv
  MLProjects/iris-machine-learning-master/Iris Visuallization result/Check the accuracy for various values of n for KNN(1).png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/Check the accuracy for various values of n for KNN(2).png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/Figure_1.png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/IRIS Andrew Curve.png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/IRIS Heatmap.png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/IRIS Histogram.png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/IRIS Parallel coordination.png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/IRIS Petal.png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/IRIS Violin plot.png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/IRIS pairplot.png
  MLProjects/iris-machine-learning-master/Iris Visuallization result/IRIS sepal.png
  MLProjects/iris-machine-learning-master/README.md
  MLProjects/iris-machine-learning-master/irisML.py
  MLProjects/readme.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#10 Design with Turtle Library.
  python/readme.md
  python/turtle-design.py
Labels: documentation, enhancement, hacktoberfest-accepted

#8 added linked list in javascript
  DSA/JavaScript/linked_list.js
  DSA/JavaScript/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted

#9 Added my webdev tribute landing page for the hacktoberfest 2021
  WebDev Projects/Tribute page/images/dr.jpg
  WebDev Projects/Tribute page/images/jp.jpg
  WebDev Projects/Tribute page/index.html
  WebDev Projects/Tribute page/style.css
Labels: documentation, enhancement, hacktoberfest-accepted

#12 Script for getting details of phone numbers
  python/phone.py
Labels: documentation, enhancement, hacktoberfest-accepted

#16 Candida18 Contributed in python
  python/Occurences.py
  python/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted

#15 Added Dice Game
  python/biased_dice.py
  python/readme.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#18 Added numpy_basic.py
  python/numpy_basic.py
  python/readme.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#17 Added Web Project To-do-list
  WebDev Projects/To-Do-list/Readme.md
  WebDev Projects/To-Do-list/app.js
  WebDev Projects/To-Do-list/date.js
  WebDev Projects/To-Do-list/index.html
  WebDev Projects/To-Do-list/package-lock.json
  WebDev Projects/To-Do-list/package.json
  WebDev Projects/To-Do-list/public/CSS/style.css
  WebDev Projects/To-Do-list/views/about.ejs
  WebDev Projects/To-Do-list/views/footer.ejs
  WebDev Projects/To-Do-list/views/header.ejs
  WebDev Projects/To-Do-list/views/list.ejs
Labels: documentation, enhancement, hacktoberfest-accepted

#21 Added deque.c
  DSA/C/deque.c
Labels: documentation, enhancement, hacktoberfest-accepted

#20 DSA Python Codes
  DSA_python/README.md
  DSA_python/stack.py
Labels: documentation, enhancement, hacktoberfest-accepted

#22 added a Dice program which I made using Python and Turtle
  python/dice_using_turtle.py
  python/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted

#24 Quick Sort Java
  DSA/Java/QuickSort.java
  DSA/Java/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted

#34 analog clock
  WebDev Projects/Analog Watch/index.html
  WebDev Projects/background-color-changer/index.html
  WebDev Projects/background-color-changer/script.js
  WebDev Projects/background-color-changer/style.css
Labels: documentation, enhancement, hacktoberfest-accepted

#30 added leap year program in C++
  DSA/C++/checkLeapYear.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#29 add my simple landing page
  WebDev Projects/Simple Landing Page/index.html
  WebDev Projects/Simple Landing Page/styles.css
Labels: enhancement, hacktoberfest-accepted

#31 Added Snake game
  WebDev Projects/snake game/Snake_Game.html
Labels: documentation, enhancement, hacktoberfest-accepted

#27 Added XC to M3U converter
  python/readme.md
  python/xc_to_m3u.py
Labels: documentation, enhancement, hacktoberfest-accepted

#36 Second branch
  WebDev Projects/FlexBox/info.txt
  WebDev Projects/FlexBox/shoeshopping.css
  WebDev Projects/FlexBox/shoeshopping.html
Labels: documentation, enhancement, hacktoberfest-accepted

#35 Binary Search Algorithm
  .gitignore
  DSA/Java/BinarySearch.java
  DSA/Java/readme.md
Labels: documentation, enhancement

#38 pomodoro clock project with reactJs
  WebDev Projects/Pomodoro-timer-with-react/.gitignore
  WebDev Projects/Pomodoro-timer-with-react/README.md
  WebDev Projects/Pomodoro-timer-with-react/package-lock.json
  WebDev Projects/Pomodoro-timer-with-react/package.json
  WebDev Projects/Pomodoro-timer-with-react/public/favicon.ico
  WebDev Projects/Pomodoro-timer-with-react/public/index.html
  WebDev Projects/Pomodoro-timer-with-react/public/logo192.png
  WebDev Projects/Pomodoro-timer-with-react/public/logo512.png
  WebDev Projects/Pomodoro-timer-with-react/public/manifest.json
  WebDev Projects/Pomodoro-timer-with-react/public/robots.txt
  WebDev Projects/Pomodoro-timer-with-react/src/App.css
  WebDev Projects/Pomodoro-timer-with-react/src/App.js
  WebDev Projects/Pomodoro-timer-with-react/src/App.test.js
  WebDev Projects/Pomodoro-timer-with-react/src/index.css
  WebDev Projects/Pomodoro-timer-with-react/src/index.js
  WebDev Projects/Pomodoro-timer-with-react/src/logo.svg
  WebDev Projects/Pomodoro-timer-with-react/src/reportWebVitals.js
  WebDev Projects/Pomodoro-timer-with-react/src/setupTests.js
Labels: documentation, enhancement, hacktoberfest-accepted

#37 added Ludo game in WebDev Projects
  WebDev Projects/JS-Ludo/images/dice1.png
  WebDev Projects/JS-Ludo/images/dice2.png
  WebDev Projects/JS-Ludo/images/dice3.png
  WebDev Projects/JS-Ludo/images/dice4.png
  WebDev Projects/JS-Ludo/images/dice5.png
  WebDev Projects/JS-Ludo/images/dice6.png
  WebDev Projects/JS-Ludo/index.html
  WebDev Projects/JS-Ludo/style.css
Labels: documentation, enhancement, hacktoberfest-accepted

#32 Added Tic Tac Toe Game made with Python
  python/readme.md
  python/tictactoe.py
Labels: documentation, enhancement

#39 Third branch
  WebDev Projects/Basic Todo Application/info.txt
  WebDev Projects/Basic Todo Application/todoapplication.css
  WebDev Projects/Basic Todo Application/todoapplication.html
  WebDev Projects/Basic Todo Application/todoapplication.js
Labels: documentation, enhancement, hacktoberfest-accepted

#41 Fourth branch
  WebDev Projects/Basic JS Application/index.css
  WebDev Projects/Basic JS Application/index.html
  WebDev Projects/Basic JS Application/index.js
  WebDev Projects/Basic JS Application/info.txt
Labels: documentation, enhancement, hacktoberfest-accepted

#42 added code for odd_even.cpp
  DSA/C++/odd_even.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#44 inplace bubble sort.cpp
  DSA/C++/bubble_sort.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#45 Added inversion count
  python/inversion_count.py
Labels: enhancement, hacktoberfest-accepted

#46 added set_bits.cpp to count set bits
  DSA/C++/set_bits.cpp
Labels: enhancement, hacktoberfest-accepted

#65 File upload using nodejs and reactjs
  WebDev Projects/File-Upload-Nodejs/client/.gitignore
  WebDev Projects/File-Upload-Nodejs/client/README.md
  WebDev Projects/File-Upload-Nodejs/client/package-lock.json
  WebDev Projects/File-Upload-Nodejs/client/package.json
  WebDev Projects/File-Upload-Nodejs/client/public/favicon.ico
  WebDev Projects/File-Upload-Nodejs/client/public/index.html
  WebDev Projects/File-Upload-Nodejs/client/public/logo192.png
  WebDev Projects/File-Upload-Nodejs/client/public/logo512.png
  WebDev Projects/File-Upload-Nodejs/client/public/manifest.json
  WebDev Projects/File-Upload-Nodejs/client/public/robots.txt
  WebDev Projects/File-Upload-Nodejs/client/src/App.css
  WebDev Projects/File-Upload-Nodejs/client/src/App.js
  WebDev Projects/File-Upload-Nodejs/client/src/App.test.js
  WebDev Projects/File-Upload-Nodejs/client/src/index.css
  WebDev Projects/File-Upload-Nodejs/client/src/index.js
  WebDev Projects/File-Upload-Nodejs/client/src/logo.svg
  WebDev Projects/File-Upload-Nodejs/client/src/reportWebVitals.js
  WebDev Projects/File-Upload-Nodejs/client/src/setupTests.js
  WebDev Projects/File-Upload-Nodejs/server/index.js
  WebDev Projects/File-Upload-Nodejs/server/package-lock.json
  WebDev Projects/File-Upload-Nodejs/server/package.json
Labels: documentation, enhancement, hacktoberfest-accepted

#47 Alarm Clock using python
  python/alarm-clock/alarm-beep.mp3
  python/alarm-clock/alarm.py
  python/readme.md
  python/url-shortener.py
Labels: documentation, enhancement, hacktoberfest-accepted

#57 DSU code added
  DSA/C++/DSU.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#48 added bits_flip.cpp
  DSA/C++/bits_flip.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#62 javascript login checker.
  javascript/login-check.js
  javascript/readme.md
  python/readme.md
  python/url_shortener.py
Labels: documentation, enhancement, hacktoberfest-accepted

#56 avl_tree_code_added
  DSA/C++/avl.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#58 Added url shortner script
  python/url_shortner.py
Labels: documentation, enhancement, hacktoberfest-accepted

#51 static weather updating website with REST API
  WebDev Projects/weather-app/README.md
  WebDev Projects/weather-app/index.html
  WebDev Projects/weather-app/script.js
  WebDev Projects/weather-app/style.css
  WebDev Projects/weather-app/weather.jfif
Labels: documentation, enhancement, hacktoberfest-accepted

#66 Added two DSA Problems and Solutions in Python
  DSA_python/Find the Runner-Up Score!/readme.md
  DSA_python/Find the Runner-Up Score!/solution.py
  DSA_python/README.md
  DSA_python/Reverse a Number/readme.md
  DSA_python/Reverse a Number/solution.py
  DSA_python/What's Your Name/readme.md
  DSA_python/What's Your Name/solution.py
Labels: documentation, enhancement, hacktoberfest-accepted

#72 Insertion Sort Algorithm
  DSA/C++/insertion sort.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#75 Counting_Sort_DSA
  DSA/C++/Counting_sort.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#78 Google Search Page
  WebDev Projects/1-google-search-page/css/styles.css
  WebDev Projects/1-google-search-page/image/bars.png
  WebDev Projects/1-google-search-page/image/google.png
  WebDev Projects/1-google-search-page/image/mic.png
  WebDev Projects/1-google-search-page/image/search.png
  WebDev Projects/1-google-search-page/index.html
Labels: documentation, enhancement, hacktoberfest-accepted

#80 :sparkles: Added binary search tree javascript class
  DSA/JavaScript/binary_search_tree.js
  DSA/JavaScript/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted

#82 added insurance company ml project
  MLProjects/Insurance_company/Buying_insurance.ipynb
  MLProjects/Insurance_company/insurance_data.csv
Labels: documentation, enhancement, hacktoberfest-accepted

#81 Created Website Availability Checker
  python/WebsiteAvailabilityChecker.py
  python/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted

#84 added a Score Keeper game programmed in javascript
  WebDev Projects/ScoreKeeper/scoreKeeper.html
  WebDev Projects/ScoreKeeper/scoreKeeper.js
Labels: documentation, enhancement, hacktoberfest-accepted

#83 Create Stack.js
  DSA/JavaScript/readme.md
  DSA/JavaScript/stack.js
Labels: documentation, enhancement, hacktoberfest-accepted

#85 added a Calculator programmed using Vanila JS,html and css.
  WebDev Projects/JS calculator/indexhtml.html
  WebDev Projects/JS calculator/script.js
  WebDev Projects/JS calculator/styles.css
Labels: documentation, enhancement, hacktoberfest-accepted

#88 Add project pokemon-list-reactjs
  WebDev Projects/pokemon-list-reactjs/README.md
  WebDev Projects/pokemon-list-reactjs/package.json
  WebDev Projects/pokemon-list-reactjs/public/index.html
  WebDev Projects/pokemon-list-reactjs/src/App.test.tsx
  WebDev Projects/pokemon-list-reactjs/src/App.tsx
  WebDev Projects/pokemon-list-reactjs/src/components/Header/index.tsx
  WebDev Projects/pokemon-list-reactjs/src/components/Header/styles.css
  WebDev Projects/pokemon-list-reactjs/src/pages/Main/index.tsx
  WebDev Projects/pokemon-list-reactjs/src/pages/Main/styles.css
  WebDev Projects/pokemon-list-reactjs/src/react-app-env.d.ts
  WebDev Projects/pokemon-list-reactjs/src/routes.tsx
  WebDev Projects/pokemon-list-reactjs/src/services/api.tsx
  WebDev Projects/pokemon-list-reactjs/tsconfig.json
Labels: documentation, enhancement, hacktoberfest-accepted

#90 Added ML Titanic project
  MLProjects/Titanic/Titanic_Gaurang.ipynb
  MLProjects/Titanic/titanic.csv
Labels: documentation, enhancement, hacktoberfest-accepted

#92 Added a class that handles Searching Objects in an array with keys at…
  DSA/JavaScript/array_of_objects_search.js
Labels: documentation, enhancement, hacktoberfest-accepted

#102 Added a Singley Linked List data structure program in C
  DSA/C/Singly_Linked_List.c
  DSA/C/Singly_Linked_List.exe
Labels: enhancement, hacktoberfest-accepted

#99 Ping Pong Game JS
  WebDev Projects/Ping-Pong-Game-JS/Screenshot .png
  WebDev Projects/Ping-Pong-Game-JS/index.html
  WebDev Projects/Ping-Pong-Game-JS/js/script.js
  WebDev Projects/Ping-Pong-Game-JS/sounds/hitSound.wav
  WebDev Projects/Ping-Pong-Game-JS/sounds/scoreSound.wav
  WebDev Projects/Ping-Pong-Game-JS/sounds/wallHitSound.wav
Labels: enhancement, hacktoberfest-accepted

#98 Created the dictionary definition checker.
  python/Dictionary_Definition.py
  python/readme.md
Labels: documentation, enhancement, hacktoberfest-accepted

#100 Kadane's Alogrithm in cpp
  DSA/C++/Kadane's Algo.cpp
Labels: enhancement, hacktoberfest-accepted

#96 Added python webscraping script to scrape weather data
  python/readme.md
  python/webscraping.py
Labels: documentation, enhancement, hacktoberfest-accepted

#106 Implementation of Queue using Template Classes in C++
  DSA/C++/Queue_Implementation_using_Template_classes_C++
Labels: documentation, enhancement, hacktoberfest-accepted

#118 Added Digital Clock in Webdev Projects
  WebDev Projects/Digital_Clock/index.html
  WebDev Projects/Digital_Clock/scripts.js
  WebDev Projects/Digital_Clock/styles.css
Labels: documentation, enhancement, hacktoberfest-accepted

#117 Added a program - to implement insertion sort using array in python
  DSA/Python/insertion_sort.py
Labels: documentation, good first issue, hacktoberfest-accepted

#125 Add Cash Register Project
  WebDev Projects/Cash_Register_Manager/index.html
  WebDev Projects/Cash_Register_Manager/index.js
  WebDev Projects/Cash_Register_Manager/styles.css
Labels: documentation, enhancement, hacktoberfest-accepted
